# Site settings
title: Mysig
header-img: img/home-bg.jpg
email: conor.e.olive@gmail.com
description: "My personal blog for random thoughts."
baseurl:
url:
twitter_username: conorolive
github_username: conorolive

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
